name: Build RK3326 Kernel (Rockchip + Initramfs)

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Repo
      uses: actions/checkout@v3

    - name: 🧰 Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          bc \
          bison \
          flex \
          libssl-dev \
          libncurses-dev \
          crossbuild-essential-arm64 \
          device-tree-compiler \
          cpio \
          unzip \
          wget \
          git

    - name: 🐧 Clone Rockchip Kernel (develop-5.10)
      run: |
        git clone --depth=1 --branch develop-5.10 https://github.com/rockchip-linux/kernel.git linux-rk3326

    - name: ➕ Add config, DTS, and Initramfs
      run: |
        # Copy .config and DTS
        cp ./src/kernel-config.txt linux-rk3326/.config
        cp ./src/r36s-clone.dts linux-rk3326/arch/arm64/boot/dts/rockchip/rk3326-r36s-clone.dts
        echo 'dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3326-r36s-clone.dtb' >> linux-rk3326/arch/arm64/boot/dts/rockchip/Makefile

        # Prepare initramfs build path
        mkdir -p linux-rk3326/initramfs
        unzip ./src/initramfs.zip -d linux-rk3326/initramfs
        cp ./src/initramfs.conf linux-rk3326/initramfs/initramfs.conf

        # Update config to embed this initramfs
        echo 'CONFIG_INITRAMFS_SOURCE="initramfs/initramfs.conf"' >> linux-rk3326/.config
        echo 'CONFIG_BLK_DEV_INITRD=y' >> linux-rk3326/.config
        echo 'CONFIG_RD_GZIP=y' >> linux-rk3326/.config
        echo 'CONFIG_INITRAMFS_COMPRESSION_GZIP=y' >> linux-rk3326/.config

    - name: ⚙️ Finalize Kernel Config
      working-directory: linux-rk3326
      run: |
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig

    - name: 🛠️ Build Kernel + DTBs + Initramfs
      working-directory: linux-rk3326
      run: |
        make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- Image dtbs

    - name: 📤 Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rk3326-kernel
        path: |
          linux-rk3326/arch/arm64/boot/Image
          linux-rk3326/arch/arm64/boot/dts/rockchip/rk3326-r36s-clone.dtb